import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./context/themeContext";

export const metadata: Metadata = {
  title: "Air Quality in Kosovo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
